/**
 * @Author: Reinier Millo Sánchez <millo>
 * @Date:   2020-04-12T21:47:45-05:00
 * @Email:  reinier.millo88@gmail.com
 * @Project: IKOABO Auth Microservice API
 * @Filename: errors.ts
 * @Last modified by:   millo
 * @Last modified time: 2020-05-03T17:25:40-05:00
 * @Copyright: Copyright 2020 IKOA Business Opportunity
 */

export enum ERRORS {
  INVALID_AUTH_SERVER = 1001,
  UNKNOWN_AUTH_SERVER_ERROR,
  INVALID_AUTHORIZATION_CODE,
  INVALID_TOKEN,
  INVALID_REFRESH_TOKEN,
  INVALID_SCOPE,
  INVALID_DOMAIN,
  INVALID_PROJECT,
  INVALID_APPLICATION,
  TOKEN_EXPIRED,
  MAX_ATTEMPTS,
  NOT_ALLOWED_SIGNIN,
  ACCOUNT_DISABLED,
  ACCOUNT_CANCELLED,
  ACCOUNT_BLOCKED,
  ACCOUNT_NOT_REGISTERED,
  ACCOUNT_ALREADY_CONFIRMED,
  EMAIL_NOT_CONFIRMED,
  INVALID_CREDENTIALS,
  EMAIL_IN_USE,
  USER_DUPLICATED,
  PROFILE_NOT_FOUND,
  RECOVER_NOT_ALLOWED,
  AUTHENTICATION_REQUIRED,
  INVALID_CODE_ERROR,
  INVALID_CODE_FULL,
}
